name: Dragon Fang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * FRI'

jobs:
  FORMAT_CHECK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: check-format
      run: ./scripts/check_code_style.sh

  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11.0.x"
          java-package: jdk
          architecture: x64
      - uses: er28-0652/setup-ghidra@master
        with:
          version: "10.1.2"
    
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 7.3
          arguments: test --info -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
